Secrets manager Update.
boldlink/terraform-aws-secretsmanager pull request #4
Opened 2022-06-07 05:42 UTC by ndegwajohn

# Description

This PR adds minimum and complete examples to the module. It also adds all standard template files.

## Features/Fixes/Patches/Changes list:

Please check the [CHANGELOG.md](https://github.com/boldlink/terraform-aws-secretsmanager/blob/feature/files-update/CHANGELOG.md#<VERSION_WITHOUT_DOTS>---<DATE>)

## Checklists:
### PR Owners Checklist:
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you checked there aren't open [Pull Requests](../../../pulls) of upstream or parallel code that will cause conflicts?
* [x] Have you updated the `CHANGELOG.md`?
* [x] Have you updated the `README.md`(s)?
* [x] OWNER: Does your submission pass?
    * [x] Pre-commit (attach logs/print screen to this PR)
    * [x] Checkov/terrascan (attach logs/print screen to this PR)
    * [x] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### PR Reviewers Checklists?
* [ ] Are all your comments/changes resolved?
* [ ] Are you happy with the OWNER checklists and additional information provided?
* [ ] Does your review tests pass?
    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?

2022-06-07 05:43 UTC, ndegwajohn commented
[checkov.txt](https://github.com/boldlink/terraform-aws-secretsmanager/files/8850388/checkov.txt)
Checkov logs

2022-06-08 13:56 UTC, hugoalmeida264 requested changes
- Add tags to the examples
 - Remove zip's and place them in code, there is a tf resource to package the code
 - Remove the ssh file, use a tf resource for it

2022-06-08 13:56 UTC, hugoalmeida264 commented on examples/binary/example.txt
> +ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMl1fu1LkwUgHghZ137jXfHqgMrx+VVhADRQGF5ru0J8tP4NlSMB6B64+C9YoEhZm+gq8LTB6BbEAPyMiVYDEdGo2pKJv369c5BR0eLluLxQo37ckUTpUCnMsRd0UBxMv88Xl0tKYrgTjOZMUbX/+YqI+Bo/VyB1g
This shouldn't be here it is better to use a terraform resource, did pre-commit failed to flag this? It should had picked it up.

2022-06-08 13:56 UTC, hugoalmeida264 commented on examples/binary/locals.tf
> +  policy   = <<POLICY
Use `jsoncode()`

2022-06-08 13:56 UTC, hugoalmeida264 commented on examples/complete/locals.tf
> +  policy   = <<POLICY
use `jsoncode()`

2022-06-08 13:56 UTC, hugoalmeida264 commented on examples/key-pair/locals.tf
> +  policy = <<POLICY
use data or `jsoncode()`

2022-06-10 16:26 UTC, hugoalmeida264 approved these changes

2022-06-10 16:26 UTC, hugoalmeida264 commented on CHANGELOG.md
> +
No line break

2022-06-10 16:26 UTC, hugoalmeida264 commented on CHANGELOG.md
> +
No line break

2022-06-10 16:26 UTC, hugoalmeida264 commented on CHANGELOG.md
> +## [1.0.2] - 2022-06-06
Add line break

2022-06-10 16:34 UTC, merged