Use rds module & CMK in complete example
boldlink/terraform-aws-secretsmanager pull request #6
Opened 2022-08-01 08:50 UTC by ndegwajohn

# Description

This PR aims to use the RDS module in complete example and also use a CMK

## Features/Fixes/Patches/Changes list:

Please check the [CHANGELOG.md](https://github.com/boldlink/terraform-aws-secretsmanager/blob/feature/use-rds-module/CHANGELOG.md#104---2022-08-01)

## Checklists:
### PR Owners Checklist:
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you checked there aren't open [Pull Requests](../../../pulls) of upstream or parallel code that will cause conflicts?
* [x] Have you updated the `CHANGELOG.md`?
* [x] Have you updated the `README.md`(s)?
* [x] OWNER: Does your submission pass?
    * [x] Pre-commit (attach logs/print screen to this PR)
    * [x] Checkov/terrascan (attach logs/print screen to this PR)
    * [x] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### PR Reviewers Checklists?
* [ ] Are all your comments/changes resolved?
* [ ] Are you happy with the OWNER checklists and additional information provided?
* [ ] Does your review tests pass?
    * [ ] Terraform resources examples build/destroy successfully with Terraform 0.14.11 minimum?

2022-08-03 22:10 UTC, patrickmukumbu requested changes
Hey @ndegwajohn please add `supporting resouces note in changelog`. See my other comments

2022-08-03 22:10 UTC, patrickmukumbu commented on examples/complete/locals.tf
> +        ]
Use locals here. See line 25 above

2022-08-03 22:10 UTC, patrickmukumbu commented on examples/complete/mysql_db.tf
> +  major_engine_version                = "8.0"
Same here, use locals

2022-08-03 22:10 UTC, patrickmukumbu commented on examples/complete/mysql_db.tf
> +  major_engine_version                = "8.0"
Same here, use locals

2022-08-03 22:10 UTC, patrickmukumbu commented on examples/complete/mysql_db.tf
> +  major_engine_version                = "8.0"
Same here, use locals

2022-08-03 22:11 UTC, patrickmukumbu requested changes
Hey @ndegwajohn please add `supporting resouces note in changelog`. See my other comments

2022-08-04 12:13 UTC, ndegwajohn commented on examples/complete/locals.tf
> +        ]
Great point @patrickmukumbu

2022-08-05 07:22 UTC, patrickmukumbu approved these changes
LGTM!

2022-08-05 07:41 UTC, merged